name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v4

      -name: setup-python
      uses: actions/setup-python

      -name: test
      run: python test.py

      -name:success message
      run: echo "successfully tested"


    

    